### ISSUE TITLE
Friction

### ISSUE THREAD

**Issue by recrudesce** [EiNSTeiN-/roadrunner-filament-sensor#9]
Printed and built this 3 times now.  There's WAY too much friction between the gears when the arm is closed, so much so that it takes a lot of force to move the filament through and is guaranteed to cause extrusion issues.   The only way I can make the filament move smoothly is to pretty much have the arm completely loose.

What am I doing wrong here ?

**Comment by recrudesce** [comment]
Closing as answered on discord :)

**Comment by jflkjjlkdsajlkdsajlkjlkjdsaljdsa** [comment]
Hello, could you please post the solution here or post a link to discord. Thanks!

**Comment by recrudesce** [comment]
I can't remember, but I think I just printed the parts at 101% size.

**Comment by EricZimmerman** [comment]
what discord?
